photo.save.dto.name.null=??? ??? ???? ???? ???.
photo.save.dto.description.null=??????? ?????? ??? ???? ???? ???.
photo.save.dto.price.null=???? ??? ???? ??? ?? ???? ????.
photo.save.dto.image.null=??? ??? ???? ??? ?? ???? ????.